server:
  port: ${PORT:8080}

spring:
  application:
    name: omnispace-backend
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:${MONGODB_URI:${MONGO_DB_URI:${MONGO_URI:mongodb://localhost:27017/omnispace}}}}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000

logging:
  level:
    root: INFO
    com.omnispace: DEBUG
    org.springframework.data.mongodb: DEBUG
